---
version: "3.8"

services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=${MYSQL_DATABASE}-dev
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 45s
      interval: 10s
      retries: 10

  backend-build:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ["CMD", -c, "npm i"]
    volumes:
      - type: bind
        source: .
        target: /usr/src/app

  backend:
    image: athle/back:backend-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - backend-build
      - db
    restart: on-failure
    environment:
      - ENV=dev
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=${MYSQL_DATABASE}-dev
      - GRAPHQL_DIR=/usr/src/app/src/infrastructure/graphql
    volumes:
      - type: bind
        source: .
        target: /usr/src/app
    ports:
      - "${BACKEND_PORT}:8080"
      - 9229:9229
    command: [bash, -c, "./wait-for.sh db:3306 -- npm run dev"]
    healthcheck:
      test: "curl -f http://localhost:8080/healthcheck || exit 1"
      start_period: 1m

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
