---
version: "3.8"

services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=${MYSQL_DATABASE}-prod
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 45s
      interval: 10s
      retries: 10

  backend:
    image: athle/back:backend-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    depends_on:
      - db
    restart: on-failure
    environment:
      - ENV=prod
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=${MYSQL_DATABASE}-prod
      - GRAPHQL_DIR=/usr/src/app/graphql
    ports:
      - "${BACKEND_PORT}:8080"
    command: [bash, -c, "./wait-for.sh db:3306 -- npm run prod"]
    healthcheck:
      test: "curl -f http://localhost:8080/healthcheck || exit 1"
      start_period: 1m
